---
title: "Chronic Absenteeism"
author: "Felicia Zhang"
date: '2018-05-15'
output:
  html_document: default
---

```{r setup, include=FALSE, warning=FALSE}
library(ggplot2) 
library(zoo)
library(reshape)
library(plyr)
library(dplyr)
library(scales) 
library(data.table)
library(signal)
library(matrixStats)
library(lme4)
library(arm)
library(broom)
library(tidyr)
library(wesanderson)
library(readxl)    
library(extrafont)

#LOAD MULTIPLE EXCEL SHEETS INTO SEPARATE DFS

#get names of sheets
sheets <- readxl::excel_sheets("~/Documents/Felicia Zhang/Felicia/Princeton/ConsultingClub/PerformanceReportsSchoolData_SY1617_FZ.xlsx")

#load in excel data as 1 big file
lst <- lapply(sheets, function(sheet) 
  readxl::read_excel("~/Documents/Felicia Zhang/Felicia/Princeton/ConsultingClub/PerformanceReportsSchoolData_SY1617_FZ.xlsx", sheet = sheet)
)

#prepare names
names(lst) <- sheets

#turn it into DF
list2env(lst, envir = .GlobalEnv)
```

```{r, echo=FALSE, warning=FALSE}
###Create Chronic Absenteeism percent for each grade, each school, and each district

#*SchoolPercent is n of students absent/n of students in the grade NOT n of students absent/n of students in the school -_-
  
poo <- EnrollmentTrendsByGrade

#remove ungraded and Total Enrollment
poo <- poo[!(poo$Grade=="Ungraded"),]
poo <- poo[!(poo$Grade=="Total Enrollment"),]

#remove the word Grade from beginning
poo$Grade <- substring(poo$Grade, 7)

#reformat poo Grade (it's written as 07 instead of 7)
poo$Grade[poo$Grade=="01"] <- "1"
poo$Grade[poo$Grade=="02"] <- "2"
poo$Grade[poo$Grade=="03"] <- "3"
poo$Grade[poo$Grade=="04"] <- "4"
poo$Grade[poo$Grade=="05"] <- "5"
poo$Grade[poo$Grade=="06"] <- "6"
poo$Grade[poo$Grade=="07"] <- "7"
poo$Grade[poo$Grade=="08"] <- "8"
poo$Grade[poo$Grade=="09"] <- "9"

poo2 <- ChronicAbsByGrade

#combine the 2
Absentgrade <- merge(poo, poo2, by=c("CountyCode","DistrictCode","SchoolCode","Grade")) # NA's match

#relabel SchoolPercent to GradePercent
names(Absentgrade)[5]<-"NumofStudents"
names(Absentgrade)[6]<-"GradePercent"

#replace grades with numeric
Absentgrade$Grade[Absentgrade$Grade=="PK"] <- "-1"
Absentgrade$Grade[Absentgrade$Grade=="KG"] <- "0"

#label missing values as NA
Absentgrade[Absentgrade == "N"] <- NA
Absentgrade[Absentgrade == "*"] <- NA

#convert all columns to numeric
Absentgrade[] <- lapply(Absentgrade, function(x) as.numeric(as.character(x)))

#convert GradePercent to decimal
Absentgrade$GradePercent <- Absentgrade$GradePercent/100

#calculate Number of students absent using total number of students * percent absent
Absentgrade$NumStudentsAbsent <- Absentgrade$NumofStudents * Absentgrade$GradePercent
Absentgrade$NumStudentsAbsent <- round(Absentgrade$NumStudentsAbsent)

#get percent absent for each school
AbsentSchool <- group_by(Absentgrade,CountyCode,DistrictCode,SchoolCode) %>%
  summarise(
    percentabsent = sum(NumStudentsAbsent) / sum(NumofStudents)
  )

#get percent absent for each district
AbsentDistrict <- group_by(Absentgrade,CountyCode,DistrictCode) %>%
  summarise(
    percentabsent = sum(NumStudentsAbsent) / sum(NumofStudents)
  )
```

##### Important information

Outcome = chronic absenteeism.  
* We have 4 ways of looking at it: county, district, school, grade  
Predictors = demographics, grades, course enrollment, negative behavior, postsecondary, school  

##### Graph information
Each dot is a school

```{r, echo=FALSE, warning=FALSE}
poo <- Absentgrade

poo2 <- group_by(poo, CountyCode, DistrictCode, Grade) %>%
  summarise(
    percentabsent = mean(GradePercent)
  )

poo.final <- group_by(poo2, Grade) %>%
  summarise(
    meanPercentabsent = mean(percentabsent,  na.rm = TRUE),
    sePercentabsent=sd(percentabsent, na.rm = TRUE)/sqrt(length(percentabsent))
  )

limits <- aes(ymax = meanPercentabsent + sePercentabsent, ymin=meanPercentabsent - sePercentabsent)

ggplot(poo.final,aes(x=factor(Grade),y=meanPercentabsent,color=factor(Grade),fill=factor(Grade)))+
  geom_bar(stat="identity")+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nChronic absenteeism rate by grade")+
  labs(x = "Grade", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,.3),breaks=seq(0,.3,.05))+
  scale_x_discrete(breaks=c("-1","0","1","2","3","4","5","6","7","8","9","10","11","12"),labels=c("PK", "KG","1","2","3","4","5","6","7","8","9","10","11","12"))+
  theme(legend.position = "none")+
  geom_errorbar(limits, width=0.25,color="black")+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(text=element_text(family="Century"))
```

```{r, echo=FALSE, warning=FALSE}
poo <- na.omit(Absentgrade)

AbsentCounty <- group_by(poo,CountyCode) %>%
  summarise(
    percentabsent = sum(NumStudentsAbsent) / sum(NumofStudents)
  )

ggplot(AbsentCounty,aes(x=factor(CountyCode),y=percentabsent,color=factor(CountyCode),fill=factor(CountyCode)))+
  geom_bar(stat="identity")+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nChronic absenteeism rate by county")+
  labs(x = "County", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,.2),breaks=seq(0,.2,.05))+
  theme(legend.position = "none")+
  theme(text=element_text(family="Century"))
```

```{r, echo=FALSE, warning=FALSE}
#PREPARE StudentToStaffRatios DF
#keeping columns: county code, district code, school code, teacher ratio, admin ratio
poo <- StudentToStaffRatios[,c(1:5)]

#label missing values as NA
poo[poo == "N"] <- NA
poo[poo == "*"] <- NA

#remove last 2 character from column :1
poo$TeacherRatio <- substr(poo$TeacherRatio,1,nchar(poo$TeacherRatio)-2)
poo$AdministratorsRatio <- substr(poo$AdministratorsRatio,1,nchar(poo$AdministratorsRatio)-2)

#convert all columns to numeric
poo[] <- lapply(poo, function(x) as.numeric(as.character(x)))

#rename columns to merge
names(poo)[1]<-"CountyCode"
names(poo)[2]<-"DistrictCode"
names(poo)[3]<-"SchoolCode"

#MERGE
poo.final <- merge(AbsentSchool, poo, by=c("CountyCode","DistrictCode","SchoolCode")) # NA's match

##########
#remove NA
pooNArm <- na.omit(poo.final)

ggplot(pooNArm,aes(x=TeacherRatio,y=percentabsent))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nStudent to Teacher ratio and chronic absenteeism")+
  labs(x = "Student:Teacher Ratio", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.1))+
  guides(color=FALSE,fill=FALSE)+
  theme(text=element_text(family="Century"))

#remove NA: adminstrator
pooNArm <- na.omit(poo.final)
ggplot(pooNArm,aes(x=AdministratorsRatio,y=percentabsent))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nStudent to Administrator ratio and chronic absenteeism")+
  labs(x = "Student:Administrator ratio", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.1))+
  guides(color=FALSE,fill=FALSE)+
  theme(text=element_text(family="Century"))
```

```{r, echo=FALSE, warning=FALSE, fig.width = 7, fig.height=10}
#PREPARE StudentToStaffRatios DF
#keeping columns: county code, district code, school code, teacher ratio, admin ratio
poo <- EnrollmentByRacialEthnicGroup

#label missing values as NA
poo[poo == "N"] <- NA
poo[poo == "*"] <- NA

#convert all columns to numeric
poo$CountyCode <- as.numeric(as.character(poo$CountyCode))
poo$DistrictCode <- as.numeric(as.character(poo$DistrictCode))
poo$SchoolCode <- as.numeric(as.character(poo$SchoolCode))
poo$Percent <- as.numeric(as.character(poo$Percent))

#convert race group to numbers
poo$ethnic <- 1
poo$ethnic[poo$RacialAndEthnicGroup=="Asian"] <- 2
poo$ethnic[poo$RacialAndEthnicGroup=="Black or African American"] <- 3 
poo$ethnic[poo$RacialAndEthnicGroup=="Hispanic"] <- 4 
poo$ethnic[poo$RacialAndEthnicGroup=="Native Hawaiian or Pacific Islander"] <- 5 
poo$ethnic[poo$RacialAndEthnicGroup=="Two or More Races"] <- 6 
poo$ethnic[poo$RacialAndEthnicGroup=="White"] <- 7 

#MERGE
poo.final <- merge(AbsentSchool, poo, by=c("CountyCode","DistrictCode","SchoolCode")) # NA's match

#convert percent to decimal
poo.final$percent2 <- poo.final$Percent/100

##########
#remove NA
pooNArm <- na.omit(poo.final)
pooNArm$percent2 <- round(pooNArm$percent2, 2)
label <- c(`1` = "American Indian or Alaska Native",`2` = "Asian",`3` = "Black or African American",`4` = "Hispanic",`5` = "Native Hawaiian or Pacific Islander",`6` = "Two or More Races",`7` = "White")

ggplot(pooNArm,aes(x=percent2,y=percentabsent,color=factor(ethnic),fill=factor(ethnic)))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nEthnicity and chronic absenteeism")+
  labs(x = "Percent of ethnic group", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  scale_x_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  facet_wrap(~ethnic, ncol=2,labeller = as_labeller(label))+
  theme(text=element_text(family="Century"))+
  theme(legend.position = "none")

#remove 0s
poo2 <- subset(pooNArm, percent2 > 0)

ggplot(poo2,aes(x=percent2,y=percentabsent,color=factor(ethnic),fill=factor(ethnic)))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nEthnicity and chronic absenteeism (removed 0s)")+
  labs(x = "Percent of ethnic group", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  scale_x_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  facet_wrap(~ethnic, ncol=2,labeller = as_labeller(label))+
  theme(text=element_text(family="Century"))+
  theme(legend.position = "none")
```

```{r, echo=FALSE, warning=FALSE}
#PREPARE DF, only keep male or female
poo <- subset(EnrollmentTrendsByStudentGroup, StudentGroup == "Male" | StudentGroup == "Female")

#label missing values as NA
poo[poo == "N"] <- NA
poo[poo == "*"] <- NA

#convert all columns to numeric
poo$CountyCode <- as.numeric(as.character(poo$CountyCode))
poo$DistrictCode <- as.numeric(as.character(poo$DistrictCode))
poo$SchoolCode <- as.numeric(as.character(poo$SchoolCode))
poo$Percent <- as.numeric(as.character(poo$Percent))

#convert gender to numbers
poo$gender <- 1
poo$gender[poo$StudentGroup=="Female"] <- 2

#MERGE
poo.final <- merge(AbsentSchool, poo, by=c("CountyCode","DistrictCode","SchoolCode")) # NA's match

#convert percent to decimal
poo.final$percent2 <- poo.final$Percent/100

##########
#remove NA
pooNArm <- na.omit(poo.final)

label <- c(`1` = "Male",`2` = "Female")

ggplot(pooNArm,aes(x=percent2,y=percentabsent,color=factor(gender),fill=factor(gender)))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nGender and chronic absenteeism")+
  labs(x = "Percent", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  scale_x_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  facet_wrap(~gender, ncol=2,labeller = as_labeller(label))+
  theme(strip.text = element_text(size=14))+
  theme(legend.position="none")+
  theme(text=element_text(family="Century"))
```

```{r, echo=FALSE, warning=FALSE, fig.width=7, fig.height=10}
#Economically Disadvantaged Students, English Learners, Homeless Students, Migrant Students, Students in Foster Care, Military-Connected Students, Students with Disabilities
poo <- subset(EnrollmentTrendsByStudentGroup, StudentGroup != "Male" & StudentGroup != "Female")

#label missing values as NA
poo[poo == "N"] <- NA
poo[poo == "*"] <- NA

#convert all columns to numeric
poo$CountyCode <- as.numeric(as.character(poo$CountyCode))
poo$DistrictCode <- as.numeric(as.character(poo$DistrictCode))
poo$SchoolCode <- as.numeric(as.character(poo$SchoolCode))
poo$Percent <- as.numeric(as.character(poo$Percent))

#convert race group to numbers
poo$group <- 1
poo$group[poo$StudentGroup=="English Learners"] <- 2
poo$group[poo$StudentGroup=="Homeless Students"] <- 3 
poo$group[poo$StudentGroup=="Migrant Students"] <- 4 
poo$group[poo$StudentGroup=="Military-Connected Students"] <- 5 
poo$group[poo$StudentGroup=="Students in Foster Care"] <- 6 
poo$group[poo$StudentGroup=="Students with Disabilities"] <- 7 

#MERGE
poo.final <- merge(AbsentSchool, poo, by=c("CountyCode","DistrictCode","SchoolCode")) # NA's match

#convert percent to decimal
poo.final$percent2 <- poo.final$Percent/100

##########
#remove NA
pooNArm <- na.omit(poo.final)

label <- c(`1` = "Economically Disadvantaged Students",`2` = "English Learners",`3` = "Homeless Students",`4` = "Migrant Students",`5` = "Military-Connected Students",`6` = "Students in Foster Care",`7` = "Students with Disabilities")

ggplot(pooNArm,aes(x=percent2,y=percentabsent,color=factor(group),fill=factor(group)))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nStudent group and chronic absenteeism")+
  labs(x = "Percent", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  scale_x_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  facet_wrap(~group, ncol=2,labeller = as_labeller(label))+
  theme(legend.position="none")+
  theme(text=element_text(family="Century"))
  
```

```{r, echo=FALSE, warning=FALSE}
poo <- ELALiteracyPerformanceByGrade

#label missing values as NA
poo[poo == "N"] <- NA
poo[poo == "*"] <- NA

#convert all columns to numeric
poo$`County Code` <- as.numeric(as.character(poo$`County Code`))
poo$`District Code` <- as.numeric(as.character(poo$`District Code`))
poo$`School Code` <- as.numeric(as.character(poo$`School Code`))
poo$ValidScores <- as.numeric(as.character(poo$ValidScores))

poo2 <- group_by(poo, `County Code`, `District Code`, `School Code`) %>%
  summarise(
    ELAScore = mean(ValidScores, na.rm = TRUE)
  )

#rename columns to merge
names(poo2)[1]<-"CountyCode"
names(poo2)[2]<-"DistrictCode"
names(poo2)[3]<-"SchoolCode"

#MERGE
roo <- merge(AbsentSchool, poo2, by=c("CountyCode","DistrictCode","SchoolCode")) # NA's match

#PLOT
pooNArm <- na.omit(roo)

ggplot(pooNArm,aes(x=ELAScore,y=percentabsent))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nELA performance and chronic absenteeism")+
  labs(x = "ELA Score", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  theme(text=element_text(family="Century"))
```

```{r, echo=FALSE, warning=FALSE}
###########################2. Math Scores
poo <- MathPerformanceByGradeTest

#label missing values as NA
poo[poo == "N"] <- NA
poo[poo == "*"] <- NA

#convert all columns to numeric
poo$`County Code` <- as.numeric(as.character(poo$`County Code`))
poo$`District Code` <- as.numeric(as.character(poo$`District Code`))
poo$`School Code` <- as.numeric(as.character(poo$`School Code`))
poo$ValidScores <- as.numeric(as.character(poo$ValidScores))

poo2 <- group_by(poo, `County Code`, `District Code`, `School Code`) %>%
  summarise(
    MathScore = mean(ValidScores, na.rm = TRUE)
  )

#rename columns to merge
names(poo2)[1]<-"CountyCode"
names(poo2)[2]<-"DistrictCode"
names(poo2)[3]<-"SchoolCode"

#MERGE
roo2 <- merge(AbsentSchool, poo2, by=c("CountyCode","DistrictCode","SchoolCode")) # NA's match

#PLOT
pooNArm <- na.omit(roo2)

ggplot(pooNArm,aes(x=MathScore,y=percentabsent))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nMath score and chronic absenteeism")+
  labs(x = "Math Score", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  theme(text=element_text(family="Century"))
```

```{r, echo=FALSE, warning=FALSE}
#################3. English Language Proficiency Test
poo <- EnglishLanguageProficiencyTest

#label missing values as NA
poo[poo == "N"] <- NA
poo[poo == "*"] <- NA

#replace 5+ to 5
poo$YearsInDistrict[poo$YearsInDistrict=="5+"] <- "5"

#convert all columns to numeric
poo[] <- lapply(poo, function(x) as.numeric(as.character(x)))

#rename columns to merge
names(poo)[1]<-"CountyCode"
names(poo)[2]<-"DistrictCode"
names(poo)[3]<-"SchoolCode"
names(poo)[5]<-"NumStudentsTested"
names(poo)[6]<-"PercentBelow4.5"
names(poo)[7]<-"PercentAbove4.5"

poo2 <- group_by(poo, CountyCode, DistrictCode, SchoolCode) %>%
  summarise(
    EngProfTest.Below = mean(PercentBelow4.5, na.rm = TRUE),
    EngProfTest.Above = mean(PercentAbove4.5, na.rm = TRUE)
  )

#convert number to decimal
poo2$EngProfTest.Below <- poo2$EngProfTest.Below/100
poo2$EngProfTest.Above <- poo2$EngProfTest.Above/100

#MERGE
roo3 <- merge(AbsentSchool, poo2, by=c("CountyCode","DistrictCode","SchoolCode")) # NA's match

#PLOT
pooNArm <- na.omit(roo3)

ggplot(pooNArm,aes(x=EngProfTest.Below,y=percentabsent))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nEnglish Language Proficiency Test and chronic absenteeism")+
  labs(x = "Percent below proficiency (i.e. below 4.5)", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  scale_x_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  theme(text=element_text(family="Century"))
```

```{r, echo=FALSE, warning=FALSE}
#####################4. Biology
#only care about percentage in terms of entire school population
poo <- subset(Biology, StudentGroup=="Schoolwide")

#label missing values as NA
poo[poo == "N"] <- NA
poo[poo == "*"] <- NA

poo$ProficiencyPerc <- as.numeric(as.character(poo$ProficiencyPerc))

#group proficient and advanced proficient together
poo$profgroup <- 1
poo$profgroup[poo$ProficiencySubgroup=="Partially Proficient"] <- 0

poo2 <- group_by(poo, CountyCode, DistrictCode, SchoolCode, profgroup) %>%
  summarise(
    ProfPercent = sum(ProficiencyPerc, na.rm = TRUE)
  )

#schools that were partially proficient
poo3 <- subset(poo2, profgroup==0)
poo3$profgroup <- NULL
names(poo3)[4]<-"PercentBelowProfBio"
poo3[] <- lapply(poo3, function(x) as.numeric(as.character(x)))

#MERGE
roo4 <- merge(AbsentSchool, poo3, by=c("CountyCode","DistrictCode","SchoolCode")) # NA's match
roo4$PercentBelowProfBio <- roo4$PercentBelowProfBio/100

##########
pooNArm <- na.omit(roo4)

ggplot(pooNArm,aes(x=PercentBelowProfBio,y=percentabsent))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nBiology proficiency and chronic absenteeism")+
  labs(x = "Percent of students below Biology proficiency level", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  scale_x_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  theme(text=element_text(family="Century"))
  
#remove 0%
poo.final <- subset(pooNArm, PercentBelowProfBio > 0)

ggplot(poo.final,aes(x=PercentBelowProfBio,y=percentabsent))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nBiology proficiency and chronic absenteeism (removing 0s)")+
  labs(x = "Percent of students below Biology proficiency level", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  scale_x_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  theme(text=element_text(family="Century"))

#Biology grades on chronic absenteeism **
#Looks like we might have something here
```

```{r, echo=FALSE, warning=FALSE}
#Violence Vandalism HIB Susbtance
#only care about percentage in terms of entire school population
poo <- ViolenceVandalismHIBSubstanceOf

#label missing values as NA
poo[poo == "N"] <- NA
poo[poo == "*"] <- NA

#convert to numeric
poo[] <- lapply(poo, function(x) as.numeric(as.character(x)))

#rename columns to merge
names(poo)[1]<-"CountyCode"
names(poo)[2]<-"DistrictCode"
names(poo)[3]<-"SchoolCode"

#MERGE
poo.final <- merge(AbsentSchool, poo, by=c("CountyCode","DistrictCode","SchoolCode")) # NA's match

##########
pooNArm <- na.omit(poo.final)

#violence
ggplot(pooNArm,aes(x=Violence,y=percentabsent))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nViolence and chronic absenteeism")+
  labs(x = "Number of Violence Incidents", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  theme(text=element_text(family="Century"))

#vandalism
ggplot(pooNArm,aes(x=Vandalism,y=percentabsent))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nVandalism and chronic absenteeism")+
  labs(x = "Number of Vandalism Incidents", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  theme(text=element_text(family="Century"))

#weapons
ggplot(pooNArm,aes(x=Weapons,y=percentabsent))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nWeapons and chronic absenteeism")+
  labs(x = "Number of Weapons Incidents", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  theme(text=element_text(family="Century"))

#substance
ggplot(pooNArm,aes(x=Substances,y=percentabsent))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nSubstance and chronic absenteeism")+
  labs(x = "Number of Substances Incidents", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  theme(text=element_text(family="Century"))

#Harassment, Intimidation, Bullying (HIB)
ggplot(pooNArm,aes(x=`Harassment, Intimidation, Bullying (HIB)`,y=percentabsent))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nHarassment, Intimidation, Bullying (HIB) and chronic absenteeism")+
  labs(x = "Number of HIB Incidents", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  theme(text=element_text(family="Century"))

#`Total Unique Incidents`
ggplot(pooNArm,aes(x=`Total Unique Incidents`,y=percentabsent))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nTotal Unique Incidents and chronic absenteeism")+
  labs(x = "Number of Total Unique Incidents", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  theme(text=element_text(family="Century"))

#`Incidents Per 100 Students Enrolled`
ggplot(pooNArm,aes(x=`Incidents Per 100 Students Enrolled`,y=percentabsent))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nRate of Incidents and chronic absenteeism")+
  labs(x = "Incidents Per 100 Students Enrolled", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  theme(text=element_text(family="Century"))

#remove 0s 
poo2 <- subset(pooNArm, `Incidents Per 100 Students Enrolled` > 0)
ggplot(poo2,aes(x=`Incidents Per 100 Students Enrolled`,y=percentabsent))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nRate of Incidents and chronic absenteeism (removed 0s)")+
  labs(x = "Incidents Per 100 Students Enrolled", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  theme(text=element_text(family="Century"))
```

```{r, echo=FALSE, warning=FALSE}
#####student suspension
poo <- StudentSuspensionRates

#label missing values as NA
poo[poo == "N"] <- NA
poo[poo == "*"] <- NA

#convert all columns to numeric
poo[] <- lapply(poo, function(x) as.numeric(as.character(x)))

#rename columns to merge
names(poo)[1]<-"CountyCode"
names(poo)[2]<-"DistrictCode"
names(poo)[3]<-"SchoolCode"

#MERGE
poo.final <- merge(AbsentSchool, poo, by=c("CountyCode","DistrictCode","SchoolCode")) # NA's match
poo.final$StudentSuspensionRate <- poo.final$StudentSuspensionRate /100

#PLOT
pooNArm <- na.omit(poo.final)

ggplot(pooNArm,aes(x=StudentSuspensionRate,y=percentabsent))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nStudent suspension and chronic absenteeism")+
  labs(x = "Student Suspension Rate", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  scale_x_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  theme(text=element_text(family="Century"))

```

```{r, echo=FALSE, warning=FALSE}
###Drop out rates
poo <- subset(DropoutRateTrends, SchoolYear=="2016-2017")

#label missing values as NA
poo[poo == "N"] <- NA
poo[poo == "*"] <- NA

#remove column
poo$SchoolYear <- NULL

#convert all columns to numeric
poo[] <- lapply(poo, function(x) as.numeric(as.character(x)))

#rename columns to merge
names(poo)[1]<-"CountyCode"
names(poo)[2]<-"DistrictCode"
names(poo)[3]<-"SchoolCode"

#MERGE
poo.final <- merge(AbsentSchool, poo, by=c("CountyCode","DistrictCode","SchoolCode")) # NA's match

#convert number to decimal
poo.final$SchoolRate <- poo.final$SchoolRate/100

#PLOT
pooNArm <- na.omit(poo.final)

ggplot(pooNArm,aes(x=SchoolRate,y=percentabsent))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nDrop out rate and chronic absenteeism")+
  labs(x = "Drop out rate", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  scale_x_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  theme(text=element_text(family="Century"))

```

```{r, echo=FALSE, warning=FALSE}
poo <- GraduationRates[c(1:5)]
poo2 <- subset(poo, StudentGroup=="Schoolwide")

#label missing values as NA
poo2[poo2 == "N"] <- NA
poo2[poo2 == "*"] <- NA

#remove column
poo2$StudentGroup <- NULL

#convert all columns to numeric
poo2[] <- lapply(poo2, function(x) as.numeric(as.character(x)))

#rename columns to merge
names(poo2)[1]<-"CountyCode"
names(poo2)[2]<-"DistrictCode"
names(poo2)[3]<-"SchoolCode"

#MERGE
poo.final <- merge(AbsentSchool, poo2, by=c("CountyCode","DistrictCode","SchoolCode")) # NA's match

#convert number to decimal
poo.final$`School-Class of 2017: 4-Year Rate` <- poo.final$`School-Class of 2017: 4-Year Rate`/100

#PLOT
pooNArm <- na.omit(poo.final)

ggplot(pooNArm,aes(x=`School-Class of 2017: 4-Year Rate`,y=percentabsent))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nClass of 2017 Graduation Rate and chronic absenteeism")+
  labs(x = "Graduation Rate", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  scale_x_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  theme(text=element_text(family="Century"))

#removing 100% graduation rate schools
poo1 <- subset(pooNArm, `School-Class of 2017: 4-Year Rate` < 1)

ggplot(poo1,aes(x=`School-Class of 2017: 4-Year Rate`,y=percentabsent))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nClass of 2017 Graduation Rate on chronic absenteeism (removing 1s)")+
  labs(x = "Graduation Rate", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  scale_x_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  theme(text=element_text(family="Century"))
```

```{r, echo=FALSE, warning=FALSE}
#Postseondary enrollment fall after graduation on chronic absenteeism ***
poo <- PostsecondaryEnrRatesFall[c(1:5)]
poo2 <- subset(poo, StudentGroup=="Schoolwide")

#label missing values as NA
poo2[poo2 == "N"] <- NA
poo2[poo2 == "*"] <- NA

#remove column
poo2$StudentGroup <- NULL

#convert all columns to numeric
poo2[] <- lapply(poo2, function(x) as.numeric(as.character(x)))

#rename columns to merge
names(poo2)[1]<-"CountyCode"
names(poo2)[2]<-"DistrictCode"
names(poo2)[3]<-"SchoolCode"

#MERGE
poo.final <- merge(AbsentSchool, poo2, by=c("CountyCode","DistrictCode","SchoolCode")) # NA's match

#convert number to decimal
poo.final$EnrolledPercent <- poo.final$EnrolledPercent/100

#PLOT
pooNArm <- na.omit(poo.final)

ggplot(pooNArm,aes(x=EnrolledPercent, y=percentabsent))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nPercent enrolled in postsecondary education and chronic absenteeism")+
  labs(x = "Percent enrolled in postsecondary education by Fall after grad", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  scale_x_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  theme(text=element_text(family="Century"))

```

```{r, echo=FALSE, warning=FALSE}
###SAT SCORES
poo <- `PSAT-SAT-ACTPerformance`[c(1:6)]
poo2 <- subset(poo, Test=="SAT")

#label missing values as NA
poo2[poo2 == "N"] <- NA
poo2[poo2 == "*"] <- NA

#remove column
poo2$Test <- NULL

#relabel subject
poo2$subject2 <- 1 #Reading and Writing
poo2$subject2[poo2$Subject=="Math"] <- 2 #Math

#convert all columns to numeric
poo2$County_Code <- as.numeric(as.character(poo2$County_Code))
poo2$District_Code <- as.numeric(as.character(poo2$District_Code))
poo2$School_Code <- as.numeric(as.character(poo2$School_Code))
poo2$School_Avg <- as.numeric(as.character(poo2$School_Avg))
poo2$subject2 <- as.numeric(as.character(poo2$subject2))

#rename columns to merge
names(poo2)[1]<-"CountyCode"
names(poo2)[2]<-"DistrictCode"
names(poo2)[3]<-"SchoolCode"

#MERGE
poo.final <- merge(AbsentSchool, poo2, by=c("CountyCode","DistrictCode","SchoolCode")) # NA's match

#PLOT
pooNArm <- na.omit(poo.final)

label <- c(`1` = "Reading and Writing",`2` = "Math")

ggplot(pooNArm,aes(x=School_Avg, y=percentabsent))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nSAT Scores and chronic absenteeism")+
  labs(x = "SAT Score", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  facet_wrap(~subject2,labeller = as_labeller(label))+
  theme(strip.text = element_text(size=14))+
  theme(text=element_text(family="Century"))
```

```{r, echo=FALSE, warning=FALSE}
####ACT scores on chronic absenteeism
poo <- `PSAT-SAT-ACTPerformance`[c(1:6)]
poo2 <- subset(poo, Test=="ACT")

#label missing values as NA
poo2[poo2 == "N"] <- NA
poo2[poo2 == "*"] <- NA

#remove column
poo2$Test <- NULL

#relabel subject
poo2$subject2 <- 1 #English
poo2$subject2[poo2$Subject=="Math"] <- 2 #Math
poo2$subject2[poo2$Subject=="Reading"] <- 3 #Reading
poo2$subject2[poo2$Subject=="Science"] <- 4 #Science

#convert all columns to numeric
poo2$County_Code <- as.numeric(as.character(poo2$County_Code))
poo2$District_Code <- as.numeric(as.character(poo2$District_Code))
poo2$School_Code <- as.numeric(as.character(poo2$School_Code))
poo2$School_Avg <- as.numeric(as.character(poo2$School_Avg))
poo2$subject2 <- as.numeric(as.character(poo2$subject2))

#rename columns to merge
names(poo2)[1]<-"CountyCode"
names(poo2)[2]<-"DistrictCode"
names(poo2)[3]<-"SchoolCode"

#MERGE
poo.final <- merge(AbsentSchool, poo2, by=c("CountyCode","DistrictCode","SchoolCode")) # NA's match

#PLOT
pooNArm <- na.omit(poo.final)

label <- c(`1` = "English",`2` = "Math",`3` = "Reading",`4` = "Science")

ggplot(pooNArm,aes(x=School_Avg, y=percentabsent))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nACT Scores and chronic absenteeism")+
  labs(x = "ACT Score", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  facet_wrap(~subject2,labeller = as_labeller(label))+
  theme(strip.text = element_text(size=14))+
  theme(text=element_text(family="Century"))
```

```{r, echo=FALSE, warning=FALSE}
#####PSAT SCORES
poo <- `PSAT-SAT-ACTPerformance`[c(1:6)]
poo2 <- subset(poo, Test=="PSAT")

#label missing values as NA
poo2[poo2 == "N"] <- NA
poo2[poo2 == "*"] <- NA

#remove column
poo2$Test <- NULL

#relabel subject
poo2$subject2 <- 1 #Reading and writing
poo2$subject2[poo2$Subject=="Math"] <- 2 #Math

#convert all columns to numeric
poo2$County_Code <- as.numeric(as.character(poo2$County_Code))
poo2$District_Code <- as.numeric(as.character(poo2$District_Code))
poo2$School_Code <- as.numeric(as.character(poo2$School_Code))
poo2$School_Avg <- as.numeric(as.character(poo2$School_Avg))
poo2$subject2 <- as.numeric(as.character(poo2$subject2))

#rename columns to merge
names(poo2)[1]<-"CountyCode"
names(poo2)[2]<-"DistrictCode"
names(poo2)[3]<-"SchoolCode"

#MERGE
poo.final <- merge(AbsentSchool, poo2, by=c("CountyCode","DistrictCode","SchoolCode")) # NA's match

#PLOT
pooNArm <- na.omit(poo.final)

label <- c(`1` = "Reading and Writing",`2` = "Math")

ggplot(pooNArm,aes(x=School_Avg, y=percentabsent))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nPSAT Scores and chronic absenteeism")+
  labs(x = "PSAT Score", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  facet_wrap(~subject2,labeller = as_labeller(label))+
  theme(strip.text = element_text(size=14))+
  theme(text=element_text(family="Century"))
```

```{r, echo=FALSE, warning=FALSE}
#Teacher experience on chronic absenteeism
#keeping columns: county code, district code, school code, teacher ratio, admin ratio
poo <- TeachersExperienceCertification[,c(1:6)]

#label missing values as NA
poo[poo == "N"] <- NA
poo[poo == "*"] <- NA

#remove column
poo$TeacherCount_State <- NULL

#convert all columns to numeric
poo[] <- lapply(poo, function(x) as.numeric(as.character(x)))

#rename columns to merge
names(poo)[1]<-"CountyCode"
names(poo)[2]<-"DistrictCode"
names(poo)[3]<-"SchoolCode"

#MERGE
poo.final <- merge(AbsentSchool, poo, by=c("CountyCode","DistrictCode","SchoolCode")) # NA's match

##########
#remove NA
pooNArm <- na.omit(poo.final)
ggplot(pooNArm,aes(x=TeacherAvgYearsExpInSchool,y=percentabsent))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nTeacher Exp In School and chronic absenteeism")+
  labs(x = "Teacher Avg Years Exp In School", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.1))+
  guides(color=FALSE,fill=FALSE)+
  theme(text=element_text(family="Century"))
```


```{r, echo=FALSE, warning=FALSE, fig.width = 10, fig.height=6}
#Teacher's level of education on chronic absenteeism
poo <- TeachersAdminsLevelOfEducation
poo2 <- subset(poo, `Teachers/Admins`== "Teachers")

#label missing values as NA
poo2[poo2 == "N"] <- NA
poo2[poo2 == "*"] <- NA

#remove column
poo2$`Teachers/Admins` <- NULL

#relabel subject
poo2$education <- 1 #Bachelor
poo2$education[poo2$HighestLevelOfEducation=="Masters"] <- 2 #Masters
poo2$education[poo2$HighestLevelOfEducation=="Doctoral"] <- 3 #Masters

#convert all columns to numeric
poo2$County_Code <- as.numeric(as.character(poo2$County_Code))
poo2$District_Code <- as.numeric(as.character(poo2$District_Code))
poo2$School_Code <- as.numeric(as.character(poo2$School_Code))
poo2$HighestLevelEdPct <- as.numeric(as.character(poo2$HighestLevelEdPct))
poo2$education <- as.numeric(as.character(poo2$education))

#rename columns to merge
names(poo2)[1]<-"CountyCode"
names(poo2)[2]<-"DistrictCode"
names(poo2)[3]<-"SchoolCode"

#MERGE
poo.final <- merge(AbsentSchool, poo2, by=c("CountyCode","DistrictCode","SchoolCode")) # NA's match
poo.final$HighestLevelEdPct <- poo.final$HighestLevelEdPct /100

#PLOT
pooNArm <- na.omit(poo.final)

label <- c(`1` = "Bachelor",`2` = "Masters",`3` = "Doctoral")

ggplot(pooNArm,aes(x=HighestLevelEdPct, y=percentabsent))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nTeacher's level of education and chronic absenteeism")+
  labs(x = "Percent", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  scale_x_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  facet_wrap(~education,labeller = as_labeller(label))+
  theme(strip.text = element_text(size=14))+
  theme(text=element_text(family="Century"))
```

```{r, echo=FALSE, warning=FALSE, include=FALSE}
#Length of school day on chronic absenteeism.. work on this
poo <- SchoolDay[,c(1:5)]

#convert time to time format
poo$TypicalStartTime <- as.POSIXct(poo$TypicalStartTime, format='%I:%M')
poo$TypicalEndTime <- as.POSIXct(poo$TypicalEndTime, format='%I:%M')

#answer is in seconds i think
poo$lengthofday <- poo$TypicalEndTime - poo$TypicalStartTime

#convert it to hours
poo$lengthofday <- poo$lengthofday / 3600

#absolute
poo$lengthofday <- abs(poo$lengthofday)

#convert all columns to numeric
poo$CountyCode <- as.numeric(as.character(poo$CountyCode))
poo$DistrictCode <- as.numeric(as.character(poo$DistrictCode))
poo$SchoolCode <- as.numeric(as.character(poo$SchoolCode))
poo$lengthofday <- as.numeric(as.character(poo$lengthofday))

#MERGE
poo.final <- merge(AbsentSchool, poo, by=c("CountyCode","DistrictCode","SchoolCode")) # NA's match

#PLOT
pooNArm <- na.omit(poo.final)

ggplot(pooNArm,aes(x=lengthofday, y=percentabsent))+
  geom_point()+
  theme_bw()+
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  ggtitle("\n\nLength of school day and chronic absenteeism")+
  labs(x = "Length of days (Hr:Mins)", y = "Chronic absenteeism rate")+
  theme(plot.title = element_text(face="bold", size=14, hjust=0))+
  theme(axis.title = element_text(face="bold", size=14))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(labels=percent,limits=c(0,1),breaks=seq(0,1,.2))+
  theme(text=element_text(family="Century"))
```
